# config file for automatic testing at travis-ci.org
language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

install:
  # install dependencies
  - pip install -r requirements/development.txt --use-mirrors

  # install your own package + executables
  - pip install --editable .

script:
  # command to run tests, e.g. python setup.py test
  - python setup.py test
